apiVersion: v1
kind: Service
metadata:
  name: spire-agent
  namespace: spire
spec:
  ports:
    - name: prometheus
      port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app: spire-agent