apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: cgr.dev/chainguard/wait-for-it
          args: ["-t", "30", "spire-server:8081"]
      containers:
        - name: spire-agent
          image: ghcr.io/spiffe/spire-agent:1.5.1
          args: ["-config", "/run/spire/config/agent.conf"]
          volumeMounts:
            - name: spire-logs
              mountPath: /run/spire/logs
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
            - name: agent-certs
              mountPath: /run/spire/certs
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
            - mountPath: /var/run/secrets/tokens
              name: spire-agent
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.6.2
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: spire-logs
            mountPath: /run/spire/logs
      volumes:
        - name: spire-logs
          emptyDir: {}
        - name: spire-config
          configMap:
            name: spire-agent
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: agent-certs
          configMap:
            name: spire-certs
            items:
              - key: agent-cert.pem
                path: agent-cert.pem
              - key: agent-key.pem
                path: agent-key.pem
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: spire-agent
          projected:
            sources:
            - serviceAccountToken:
                path: spire-agent
                expirationSeconds: 600
                audience: spire-server
