apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: prometheus-server
      port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: spire-server
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server-ingress
  namespace: spire
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: spire-server
