apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spire
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    scrape_configs:
      - job_name: 'spire-server'
        metrics_path: '/'
        static_configs:
        - targets: ['spire-server.spire.svc.cluster.local:8088']

      - job_name: 'spire-agent'
        metrics_path: '/'
        static_configs:
        - targets: ['spire-agent.spire.svc.cluster.local:8089']
