apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-ingress
spec:
  type: LoadBalancer
  ports:
    - name: kibana-ui
      port: 5601
      targetPort: 5601
      protocol: TCP
  selector:
    common.k8s.elastic.co/type: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
spec:
  type: LoadBalancer
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    common.k8s.elastic.co/type: elasticsearch