apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.6.2
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    xpack.security.secureCookies: true
    xpack.security.sameSiteCookies: "None"
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
      anonymous.anonymous1:
        order: 1
        credentials:
          username: "anonymous"
          password: "anonymous"
